version: "3"

services:
  postgresql:
    image: "postgres:12"
    env_file:
        - ./.env
    volumes:
        - database-data:/var/lib/postgresql/data/
    ports:
        - "5435:5432"
    volumes:
        - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  safebull-api:
    depends_on:
      - postgresql
    build:
      context: ./api
      dockerfile: ./Dockerfile
    env_file:
     - ./.env
    ports:
    - "4477:80"
  safebull-bot:
    depends_on:
      - postgresql
    build:
      context: ./bot
      dockerfile: ./Dockerfile
    env_file:
      - ./.env

  nginx:
    depends_on:
      - safebull-api
    image: nginx:1.19.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
  