version: "3"

services:
  postgresql:
    image: "postgres:12"
    env_file:
        - ./.env
    volumes:
        - database-data:/var/lib/postgresql/data/
    ports:
        - "5435:5432"
    volumes:
        - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
  safebull-api:
    depends_on:
      - postgresql
      - nginx
    image: bitoid/safebull-api:dev
    env_file:
     - ./.env
  safebull-bot:
    depends_on:
      - postgresql
      - nginx
    image: bitoid/safebull-bot:dev
    env_file:
     - ./.env